pipeline {
    agent any

    stages {
        stage('Create Webpage') {
            steps {
                bat '''
                if not exist site mkdir site

                echo ^<!DOCTYPE html^> > site\\index.html
                echo ^<html^> >> site\\index.html
                echo ^<head^> >> site\\index.html
                echo ^<title^>Jenkins Webpage^</title^> >> site\\index.html
                echo ^</head^> >> site\\index.html
                echo ^<body style="font-family:Arial; background:#f4f6f8; text-align:center;"^> >> site\\index.html
                echo ^<h1^>🚀 Jenkins Pipeline Success^</h1^> >> site\\index.html
                echo ^<p^>This webpage was generated by Jenkins^</p^> >> site\\index.html
                echo ^</body^> >> site\\index.html
                echo ^</html^> >> site\\index.html
                '''
            }
        }

        stage('Publish Webpage') {
            steps {
                archiveArtifacts artifacts: 'site/index.html'
            }
        }
    }
}
