pipeline {
    agent any

    stages {
        stage('Create Beautiful Webpage') {
            steps {
                sh '''
                mkdir -p site
                cat <<EOF > site/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Jenkins Pipeline Success</title>
    <style>
        body {
            margin: 0;
            font-family: "Segoe UI", sans-serif;
            background: linear-gradient(135deg, #667eea, #764ba2);
            height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
        }
        .card {
            background: white;
            width: 420px;
            padding: 40px;
            border-radius: 16px;
            text-align: center;
            box-shadow: 0 20px 40px rgba(0,0,0,0.2);
        }
        h1 {
            color: #4f46e5;
        }
        p {
            color: #555;
        }
        .badge {
            margin-top: 20px;
            padding: 10px 20px;
            background: #22c55e;
            color: white;
            border-radius: 50px;
            display: inline-block;
            font-weight: bold;
        }
        footer {
            margin-top: 25px;
            font-size: 13px;
            color: #777;
        }
    </style>
</head>
<body>
    <div class="card">
        <h1>🚀 Pipeline Successful</h1>
        <p>Your Jenkins pipeline ran successfully.</p>
        <div class="badge">BUILD SUCCESS</div>
        <footer>Generated by Jenkins CI/CD</footer>
    </div>
</body>
</html>
EOF
                '''
            }
        }

        stage('Publish Webpage') {
            steps {
                archiveArtifacts artifacts: 'site/index.html', fingerprint: true
            }
        }
    }

    post {
        success {
            echo 'Webpage generated successfully'
        }
    }
}
