pipeline {
    agent any

    stages {
        stage('Create Webpage') {
            steps {
                sh '''
                mkdir -p site
                cat <<EOF > site/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Jenkins Pipeline Webpage</title>
    <style>
        body {
            font-family: Arial;
            background-color: #f4f6f8;
            text-align: center;
            padding-top: 100px;
        }
        h1 {
            color: #2563eb;
        }
        p {
            font-size: 18px;
        }
    </style>
</head>
<body>
    <h1>🚀 Jenkins Pipeline Successful</h1>
    <p>This webpage was generated by Jenkins pipeline.</p>
</body>
</html>
EOF
                '''
            }
        }

        stage('Publish Webpage') {
            steps {
                archiveArtifacts artifacts: 'site/index.html', fingerprint: true
            }
        }
    }
}
